source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
target 'Sample' do
  pod 'Texture/IGListKit', :path => '../..'
  pod 'Texture/PINRemoteImage', :path => '../..'
  pod 'Texture/Yoga', :path => '../..'
  pod 'Weaver', :path => '../../../Weaver'
  pod 'Weaver/Video', :path => '../../../Weaver'
end
